name: Test
on:
  push:
    branches:
      - main
      - develop
      - release
jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        device: ["iPhone 11"]
        scheme: ["KIImagePager"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
      - name: Build and test
        run: bundle exec fastlane scan --device "${device}" --scheme "${scheme}"
        env:
          scheme: ${{ matrix.scheme }}
          device: ${{ matrix.device }}
