name: Test
on:
  push:
    branches:
      - main
      - develop
      - release
jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=13.6,name=iPhone 11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
      - name: Build and test
        run: xcodebuild clean test -project KIImagePager.xcodeproj -scheme KIImagePager -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}
